name: CI
on:
  push:
    branches: [main]
jobs:
  build-virion:
    name: Build Virion
    permissions:
      contents: write
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: composer

      - name: Install Dependencies
        run: composer install --ignore-platform-reqs

      - name: Build Virion
        run: php -d phar.readonly=0 scripts/build-virion.php

      - name: Checkout corresponding Poggit branch
        run: |
          echo "COMMIT_MESSAGE=$(git log -1 --pretty=format:%s)" >> $GITHUB_ENV

          git fetch origin poggit/${{ github.ref_name }} || true
          git checkout -B poggit/${{ github.ref_name }} origin/poggit/${{ github.ref_name }} || git checkout -b poggit/${{ github.ref_name }}

      - name: Extract .phar file
        run: |
          mkdir -p extracted
          php -r "
            \$phar = new Phar('builds/Textify.phar');
            \$phar->extractTo('extracted', null, true);
          "

      - name: Prepare extracted files for commit
        run: |
          find . -mindepth 1 \
            ! -name ".git" ! -path "./.git/*" \
            ! -name "extracted" ! -path "./extracted/*" \
            ! -name "README.md" \
            ! -name "LICENSE" \
            -exec rm -rf {} + \
            || true
          cp -r extracted/* .
          rm -rf extracted

      - name: Generate Poggit-CI Manifest
        run: |
          cat > .poggit.yml <<EOL
          --- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/nicholass003/Textify
          build-by-default: true
          branches:
            - poggit/${{ github.ref_name }}
            projects:
              Textify:
                path: ""
                model: virion
                type: library
          ...

      - name: Commit and Push Extracted Files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add --force .

          git commit -m "$COMMIT_MESSAGE" || git commit --allow-empty -m "$COMMIT_MESSAGE"

          git push --force origin poggit/${{ github.ref_name }}