name: CI
on:
  push:
    branches: [main]
jobs:
  build-virion:
    name: Build Virion
    permissions:
      contents: write
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: composer

      - name: Install Dependencies
        run: composer install --ignore-platform-reqs

      - name: Build Virion
        run: php -d phar.readonly=0 scripts/build-virion.php

      - name: Remove .phar from commit
        run: |
          echo "builds/" >> .gitignore
          rm -rf builds/Textify.phar
          git rm --cached builds/Textify.phar || true

      - name: Push to poggit/stable
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          COMMIT_MESSAGE=$(git log -1 --pretty=format:%s)
          
          git fetch origin poggit/stable || true
          git checkout -B poggit/stable origin/poggit/stable || git checkout -b poggit/stable
          
          git add .
          
          git commit -m "$COMMIT_MESSAGE"
          
          git push --force origin poggit/stable